import streamlit as st
import pandas as pd
import os
import io

# --- PORTABLE DATA PATHS ---
# Note: Paths are relative, assuming data files are in the 'data' folder 
# and this app.py is in the 'src' folder (../data/filename.csv)

OUTPUT_LIST_PATH = os.path.join("..", "data", "output_list.csv")
OUTPUT_CSV_PATH = os.path.join("..", "data", "output_pdf_data.csv")
SENTIMENT_DATA_PATH = os.path.join("..", "data", "detailed_analysis_with_concession_sentiment.csv")

# --- DATA LOADING FUNCTIONS ---
# Load data, handling potential file errors gracefully
@st.cache_data
def load_data(path):
    try:
        # For professional deployment, this would be pd.read_sql
        df = pd.read_csv(path)
        df.columns = df.columns.str.strip()
        return df
    except FileNotFoundError:
        st.error(f"Error: Data file not found at {path}. Please run the ETL pipeline.")
        return pd.DataFrame()

output_list_df = load_data(OUTPUT_LIST_PATH)
df = load_data(OUTPUT_CSV_PATH)
sentiment_df = load_data(SENTIMENT_DATA_PATH)

# --- WEB APP STRUCTURE ---

# Title of the webpage (Professional Focus)
st.markdown("<h1 style='text-align: center;'>Chilean Mining Concession Data Intelligence ⛏️</h1>", unsafe_allow_html=True)
st.markdown("<h4 style='text-align: center;'>Automated ETL and Text Analytics Platform</h4>", unsafe_allow_html=True) # Removed student ID

# Link to the official Chilean Mining Bulletin webpage
st.markdown("<p style='text-align: center;'>Data Source: <a href='https://www.diariooficial.interior.gob.cl/publicaciones/' target='_blank'>Official Mining Bulletin of Chile</a></p>", unsafe_allow_html=True)

# Sidebar Navigation
st.sidebar.title('Pipeline Navigation')
selection = st.sidebar.radio("Go to", ["Home", "Extracted Data", "Text Analysis Metrics", "Edition Tracking"])

# Main content based on navigation
if selection == "Home":
    st.write(""" 
    ## Data Pipeline Overview
    This application demonstrates a **full-cycle Data Engineering and NLP pipeline** designed to convert complex, non-structured legal documents into actionable business intelligence.

    ### Project Summary:
    - **PDF Scraping & Parsing**: Automated extraction of critical data (names, regions, CVE numbers) from dynamic Chilean Official Mining Bulletin PDFs.
    - **Web Scraping**: Uses **Selenium** and **BeautifulSoup** to gather and track historical editions of the bulletin, ensuring data integrity.
    - **Text Analysis & Metrics**: Applied **Hugging Face's multilingual model** to derive **Sentiment Scores** and evaluate public perception on concession names and regions.
    - **Data Visualization**: Interactive data display using **Streamlit**, proving the end-to-end functionality of the platform.

    **Libraries Used**:
    - **Selenium**, **BeautifulSoup**, **Pandas**, **pdfplumber**, **requests**, **Streamlit**, **transformers** (for NLP)
    """)

elif selection == "Extracted Data":
    st.write("### Extracted Data Sample")
    st.write("A sample of the structured data generated by the ETL pipeline.")

    if not df.empty:
        st.dataframe(df)
    else:
        st.warning("Data not available. Please ensure the extraction pipeline has been run successfully.")

elif selection == "Text Analysis Metrics":
    st.write(""" 
    ## Text Analysis & Sentiment Metrics
    This section showcases the **transformation layer (T)** of the ETL, where unstructured text is converted into quantifiable metrics.

    ### Metric Generation:
    - **Sentiment Analysis**: Applied **Hugging Face's multilingual BERT model** to assign sentiment (positive, neutral, negative) to concession names and regions.
    - **Importance Scoring**: A structured score is mapped (-2 to +2), providing a clear, quantitative gauge of public perception for each mining asset.
    - **Output**: The results are presented in a clean, query-ready format for further spatial or economic analysis.
    """)

    if not sentiment_df.empty:
        st.write("### Sentiment Analysis Results")
        st.dataframe(sentiment_df)
    else:
        st.warning("Sentiment data not available. Please check the data loading path.")

elif selection == "Edition Tracking":
    st.write("### Bulletin Edition Tracking")
    st.write("Overview of the historical editions successfully scraped, demonstrating the stability of the Web Scraping process.")

    if not output_list_df.empty:
        st.dataframe(output_list_df)

        st.write("#### Download Data Snapshot")
        # Function to convert DataFrame to CSV for download button
        @st.cache_data
        def convert_df_to_csv(df_to_convert):
            return df_to_convert.to_csv(index=False).encode('utf-8')

        csv_data = convert_df_to_csv(output_list_df)

        st.download_button(
            label="Download Editions CSV",
            data=csv_data,
            file_name='edition_tracking_snapshot.csv',
            mime='text/csv'
        )
    else:
        st.warning("Edition tracking data not available.")

# --- Future Development Note (Optional, but shows vision for SQL migration) ---
st.sidebar.markdown(
    """
    ***
    **Future State:** Data persistence will be migrated from flat files 
    to a PostgreSQL/PostGIS database for scalable spatial querying.
    """
)